### ISSUE TITLE
Wrong SPI host

### ISSUE THREAD

**Issue by step0035** [VedantParanjape/esp-epaper-display#2]
Hi there, I ran into a fault when I need to init SPI for a second time after adding some sleep/wake features

- The issue is in line 72 of epdif.cpp
`spi_bus_free(VSPI_HOST);`

- I believe that this should be
`spi_bus_free(HSPI_HOST);`
since the HSPI host was used during bus initialization in line 100
`ret=spi_bus_initialize(HSPI_HOST, &buscfg, 0);`

**Comment by VedantParanjape** [comment]
Fixed in #3
