### ISSUE TITLE
SPI Fails for new ESP-IDF 

### ISSUE THREAD

**Issue by IsaacNez** [VedantParanjape/esp-epaper-display#4]
Hi,

First, thanks for this amazing port! It saved me a lot of headaches. For the past year, I have been using it over ESP-IDF v4.3 and v4.4.2 but I had to do some minor changes to make it run. 

First, the includes for `epdif.h` and other alike had to be changed to `epdif.cpp` and similar. Likewise, I had to remove the definiton of `SPI_HOST` because it is now defined under `spi_types.h`

It would be my privilege to contribute to the project. I have already fixed them on my local branch but I lack the permissions to push it to the repo and then open a pull request.

I also plan to introduce version checking to make it more adaptable. 

Let me know if you are interested!

**Comment by VedantParanjape** [comment]
Hey Thanks for the kind words, I'm glad it helped.

You can fork my repo and then push the changes to the repo. After this open a PR. Let me know if you need any more help.

**Comment by cefoot** [comment]
@IsaacNez could you make you changes available or describe in more detail what you did? Especially I don't know what you mean by "First, the includes for epdif.h and other alike had to be changed to epdif.cpp and similar"

**Comment by IsaacNez** [comment]
Hi @cefoot, I have made the changes available on #5. Sorry for not doing it sooner, I have had quite busy weeks.

**Comment by VedantParanjape** [comment]
Closing this as solved, thanks for the PR @IsaacNez
